// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HoHDashboard.server.Models;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BeneficiaryMaster> BeneficiaryMasters { get; set; }

    public virtual DbSet<ComponentMaster> ComponentMasters { get; set; }

    public virtual DbSet<UserLogin> UserLogins { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BeneficiaryMaster>(entity =>
        {
            entity.HasKey(e => e.CompId).HasName("PK__Benefici__AD362A1680A12292");

            entity.ToTable("BeneficiaryMaster");

            entity.Property(e => e.AccountNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.AreaNosPerUnit).HasColumnType("numeric(18, 4)");
            entity.Property(e => e.BeneficiaryName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BlockName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Category)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.ClaimID)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ComponantName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CropName).HasMaxLength(50);
            entity.Property(e => e.DistrictName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FamilyID)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.FatherName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FyYear)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Gender)
                .HasMaxLength(6)
                .IsUnicode(false);
            entity.Property(e => e.IFSC_Code)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MobileNo)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.PANCard)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.SchemeName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SubsidyAmountToFarmer).HasColumnType("numeric(18, 4)");
            entity.Property(e => e.TransactionType)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VillageName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ComponentMaster>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Componen__3214EC27681766DF");

            entity.ToTable("ComponentMaster");

            entity.Property(e => e.ComponentCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ComponentName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserLogin>(entity =>
        {
            entity.HasKey(e => e.UserID).HasName("PK__UserLogi__1788CCACF6B85195");

            entity.ToTable("UserLogin");

            entity.HasIndex(e => e.UserName, "UQ__UserLogi__C9F28456EEA4664E").IsUnique();

            entity.Property(e => e.UserID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ID).ValueGeneratedOnAdd();
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDateTime).HasColumnType("datetime");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}