// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoHDashboard.server.Models;

public partial class BeneficiaryMaster
{
    public string FyYear { get; set; }

    public string SchemeName { get; set; }

    public string ComponantName { get; set; }

    public string BeneficiaryName { get; set; }

    public string FatherName { get; set; }

    public string VillageName { get; set; }

    public string BlockName { get; set; }

    public string DistrictName { get; set; }

    public string MobileNo { get; set; }

    public string PANCard { get; set; }

    public string FamilyID { get; set; }

    public string ClaimID { get; set; }

    public string Category { get; set; }

    public string Gender { get; set; }

    public decimal? AreaNosPerUnit { get; set; }

    public decimal? SubsidyAmountToFarmer { get; set; }

    public string AccountNumber { get; set; }

    public string IFSC_Code { get; set; }

    public int? UIDByDepartment { get; set; }

    public string CropName { get; set; }

    public string TransactionType { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTimeOffset? CreatedDateTime { get; set; }

    public DateTimeOffset? UpdatedDateTime { get; set; }

    public bool? IsDeleted { get; set; }

    public int CompId { get; set; }
}