// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoHDashboard.server.Models;

public partial class ComponentMaster
{
    public int ID { get; set; }

    public string ComponentName { get; set; }

    public string ComponentCode { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTimeOffset? CreatedDateTime { get; set; }

    public DateTimeOffset? UpdatedDateTime { get; set; }

    public bool? IsDeleted { get; set; }
}