// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoHDashboard.server.Models;

public partial class UserLogin
{
    public int ID { get; set; }

    public Guid UserID { get; set; }

    public string UserName { get; set; }

    public string PasswordHash { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedDateTime { get; set; }

    public DateTime? UpdatedDateTime { get; set; }
}